import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar"
import BottomNav from "@/components/ui/BottomNav"
import Footer from "@/components/sections/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marcelo Rodriguez | Desarrollador Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-neutral-950 text-neutral-100">

        <div className="flex">
          {/* Sidebar — solo desktop */}
          <Sidebar />

          {/* Contenido principal — con margen izquierdo en desktop */}
          <main className="flex-1 md:ml-52 min-h-screen px-8 py-6">
            {children}
          </main>
        </div>

        {/* Bottom nav — solo móvil */}
        <BottomNav />

      <Footer />

      </body>

    </html>
  );
}
